id: P006719
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ6027
  title: འཇའ་ཚོན་སྙིང་པོའི་ཆོས་སྤྱོད
  author: ''
  volumes:
    0131d9d9aacf43cabda67e32c268fd2e:
      image_group_id: I1KG1019
      title: ''
      volume_number: 1
      total_pages: 522
      base_file: v001.txt
